name: build-rp2040
on:
  push:
    paths:
      - 'firmware/**'
  workflow_call:
defaults:
  run:
    shell: bash --noprofile --norc -x -e -o pipefail {0}
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install compiler, libraries and tools
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib srecord
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make
          cd ..
          mkdir build-boards
          cd build-boards
          PICO_BOARD=remapper cmake ..
          make remapper_dual_a
          cd ..
          mkdir build-feather
          cd build-feather
          PICO_BOARD=feather_host cmake ..
          make remapper
          cd ..
          mkdir artifacts
          mv build/*.uf2 artifacts
          mv build-boards/remapper_dual_a.uf2 artifacts/remapper_board.uf2
          mv build-feather/remapper.uf2 artifacts/remapper_feather.uf2
        working-directory: ./firmware
      - uses: actions/upload-artifact@v3
        with:
          path: firmware/artifacts/*
